#!/usr/bin/env python3
"""
convert from list to zabbix discovery json format
usage:
    cat list | ./l2d -n name
"""
import sys
import json
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('-n', '--name', required=True, help='volume name')
parser.add_argument('items', nargs='*')

args = parser.parse_args()
name = args.name
items = args.items
if not items:
    items = [x.strip() for x in sys.stdin.readlines()]

data = [{'{{#{}}}'.format(name.upper()): x} for x in items if x]
result = {'data': data}
print(json.dumps(result, indent=True))